<?php

declare(strict_types=1);

namespace Hamaelt\VirusScanner\Icap;
use Socket;

class IcapClient
{
    private string $host;

    private int $port;

    private string $service;

    Private Socket $socket;

    /**
     * IcapClient constructor.
     * @param $
     */
    public function __construct(string $host, int $port, string $service)
    {

    }

    public function connect(): bool
    {
        $this->socket = socket_create(AF_INET, SOCK_STREAM, SOL_TCP);
        return socket_connect($this->socket, $this->host, $this->port);
    }

    /**
     * `@` symbol (any error messages that might be generated by that expression will be ignored.)
     * https://www.php.net/manual/en/language.operators.errorcontrol.php
     */
    public function disconnect(): void
    {
        @socket_shutdown($this->socket);
        @socket_close($this->socket);
    }

    public function sendRequest(string $request)
    {
        return socket_write($this->socket, $request);
    }

    public function getLastSocketError(string $request): int
    {
        return socket_last_error($this->socket);
    }

    public function readResponse()
    {

    }

    public function options()
    {

    }

    public function respmod(string $filePath)
    {

    }
}